"use client";

import React, { useState, useEffect } from 'react';
import { Project } from '@/components/ProjectMarkers';
import { COUNTRIES, Country } from '@/data/countries';

export default function BackofficePage() {
    const [projects, setProjects] = useState<Project[]>([]);
    const [formData, setFormData] = useState<Partial<Project>>({
        name: '',
        lat: 0,
        lng: 0,
        status: 'active',
        details: ''
    } as any); // Type cast for simpler handled of flattened lat/lng
    const [loading, setLoading] = useState(false);
    const [message, setMessage] = useState('');

    // Country Search State
    const [searchTerm, setSearchTerm] = useState('');
    const [showSuggestions, setShowSuggestions] = useState(false);

    const fetchProjects = async () => {
        try {
            const res = await fetch('/api/projects');
            const data = await res.json();
            setProjects(data);
        } catch (err) {
            console.error('Failed to fetch projects', err);
        }
    };

    useEffect(() => {
        fetchProjects();
    }, []);

    const handleChange = (e: React.ChangeEvent<HTMLInputElement | HTMLSelectElement>) => {
        const { name, value } = e.target;
        setFormData(prev => ({ ...prev, [name]: value }));
    };

    const handleCountrySelect = (country: Country) => {
        setFormData(prev => ({
            ...prev,
            lat: country.lat,
            lng: country.lng
        } as any));
        setSearchTerm(country.name);
        setShowSuggestions(false);
    };

    const filteredCountries = COUNTRIES.filter(c =>
        c.name.toLowerCase().includes(searchTerm.toLowerCase())
    );

    const handleSubmit = async (e: React.FormEvent) => {
        e.preventDefault();
        setLoading(true);
        setMessage('');

        // Construct the payload
        // @ts-ignore
        const payload: Project = {
            // id will be generated by server
            name: formData.name || '',
            // @ts-ignore
            coords: [parseFloat(formData.lng), parseFloat(formData.lat)],
            status: formData.status as any,
            details: formData.details || ''
        };

        try {
            const res = await fetch('/api/projects', {
                method: 'POST',
                headers: { 'Content-Type': 'application/json' },
                body: JSON.stringify(payload)
            });

            if (res.ok) {
                setMessage('Project added successfully!');
                setFormData({ name: '', lat: 0, lng: 0, status: 'active', details: '' } as any);
                setSearchTerm(''); // Reset search
                fetchProjects(); // Refresh list
            } else {
                setMessage('Failed to add project.');
            }
        } catch (error) {
            setMessage('Error submitting form.');
        } finally {
            setLoading(false);
        }
    };

    return (
        <div className="h-screen bg-canvas p-8 text-white overflow-y-auto">
            <div className="max-w-4xl mx-auto">
                <h1 className="text-3xl font-bold mb-8 text-accent-cyan">Mission Control Backoffice</h1>

                <div className="grid grid-cols-1 md:grid-cols-2 gap-8">

                    {/* Add Project Form */}
                    <div className="glass-panel p-6 rounded-xl border border-white/10">
                        <h2 className="text-xl font-bold mb-4">Add New Project</h2>
                        <form onSubmit={handleSubmit} className="space-y-4">
                            <div>
                                <label className="block text-sm text-gray-400 mb-1">Project Name</label>
                                <input
                                    type="text"
                                    name="name"
                                    value={formData.name || ''}
                                    onChange={handleChange}
                                    className="w-full bg-black/30 border border-white/20 rounded px-3 py-2 focus:border-accent-cyan outline-none"
                                    required
                                />
                            </div>

                            {/* Country Search */}
                            <div className="relative">
                                <label className="block text-sm text-gray-400 mb-1">Location / Country</label>
                                <input
                                    type="text"
                                    placeholder="Search & Select Country..."
                                    value={searchTerm}
                                    onChange={(e) => {
                                        setSearchTerm(e.target.value);
                                        setShowSuggestions(true);
                                    }}
                                    onFocus={() => setShowSuggestions(true)}
                                    className="w-full bg-black/30 border border-white/20 rounded px-3 py-2 focus:border-accent-cyan outline-none"
                                />

                                {showSuggestions && searchTerm && (
                                    <div className="absolute z-50 w-full mt-1 bg-black border border-white/20 rounded-md shadow-lg max-h-48 overflow-y-auto custom-scrollbar">
                                        {filteredCountries.length > 0 ? (
                                            filteredCountries.map(country => (
                                                <div
                                                    key={country.name}
                                                    className="px-3 py-2 cursor-pointer hover:bg-accent-cyan/20 transition-colors text-sm"
                                                    onClick={() => handleCountrySelect(country)}
                                                >
                                                    {country.name}
                                                </div>
                                            ))
                                        ) : (
                                            <div className="px-3 py-2 text-gray-500 text-sm">No matches found</div>
                                        )}
                                    </div>
                                )}
                            </div>

                            <div className="grid grid-cols-2 gap-4">
                                <div>
                                    <label className="block text-sm text-gray-400 mb-1">Longitude</label>
                                    <input
                                        type="number"
                                        step="0.0001"
                                        name="lng"
                                        // @ts-ignore
                                        value={formData.lng || ''}
                                        onChange={handleChange}
                                        className="w-full bg-black/30 border border-white/20 rounded px-3 py-2 focus:border-accent-cyan outline-none"
                                        required
                                    />
                                </div>
                                <div>
                                    <label className="block text-sm text-gray-400 mb-1">Latitude</label>
                                    <input
                                        type="number"
                                        step="0.0001"
                                        name="lat"
                                        // @ts-ignore
                                        value={formData.lat || ''}
                                        onChange={handleChange}
                                        className="w-full bg-black/30 border border-white/20 rounded px-3 py-2 focus:border-accent-cyan outline-none"
                                        required
                                    />
                                </div>
                            </div>

                            <div>
                                <label className="block text-sm text-gray-400 mb-1">Status</label>
                                <select
                                    name="status"
                                    value={formData.status || 'active'}
                                    onChange={handleChange}
                                    className="w-full bg-black/30 border border-white/20 rounded px-3 py-2 focus:border-accent-cyan outline-none"
                                >
                                    <option value="active">Active</option>
                                    <option value="maintenance">Maintenance</option>
                                    <option value="deployed">Deployed</option>
                                </select>
                            </div>

                            <div>
                                <label className="block text-sm text-gray-400 mb-1">Details</label>
                                <input
                                    type="text"
                                    name="details"
                                    value={formData.details || ''}
                                    onChange={handleChange}
                                    className="w-full bg-black/30 border border-white/20 rounded px-3 py-2 focus:border-accent-cyan outline-none"
                                />
                            </div>

                            <button
                                type="submit"
                                disabled={loading}
                                className="w-full bg-accent-cyan/20 hover:bg-accent-cyan/40 text-accent-cyan font-bold py-2 rounded transition-colors border border-accent-cyan/50"
                            >
                                {loading ? 'Processing...' : 'Add Project'}
                            </button>

                            {message && <p className="text-center text-sm mt-2">{message}</p>}
                        </form>
                    </div>

                    {/* Current Projects List */}
                    <div className="glass-panel p-6 rounded-xl border border-white/10">
                        <h2 className="text-xl font-bold mb-4">Current Projects ({projects.length})</h2>
                        <div className="space-y-3 max-h-[600px] overflow-y-auto pr-2 custom-scrollbar">
                            {projects.map(p => (
                                <div key={p.id} className="p-3 bg-white/5 rounded border border-white/5 hover:border-white/20 transition-colors">
                                    <div className="flex justify-between items-start">
                                        <h3 className="font-bold text-white">{p.name}</h3>
                                        <span className={`text-xs px-2 py-0.5 rounded-full ${p.status === 'active' ? 'bg-green-500/20 text-green-300' :
                                            p.status === 'maintenance' ? 'bg-yellow-500/20 text-yellow-300' :
                                                'bg-blue-500/20 text-blue-300'
                                            }`}>
                                            {p.status}
                                        </span>
                                    </div>
                                    <div className="text-xs text-gray-400 mt-1">
                                        {p.coords[0].toFixed(2)}, {p.coords[1].toFixed(2)}
                                    </div>
                                    <div className="text-sm text-gray-300 mt-1">{p.details}</div>
                                </div>
                            ))}
                        </div>
                    </div>

                </div>

                {/* Conflict Zones Management */}
                <div className="mt-8 glass-panel p-6 rounded-xl border border-white/10">
                    <h2 className="text-xl font-bold mb-4">Conflict Zones Management</h2>
                    <p className="text-gray-400 text-sm mb-4">Draw polygons on the map to define conflict zones.</p>

                    <div className="h-[500px] w-full relative rounded-xl overflow-hidden border border-white/20">
                        <ConflictMapEditor />
                    </div>
                </div>
            </div>
        </div>
    );
}

import Map, { NavigationControl } from 'react-map-gl/maplibre';
import 'maplibre-gl/dist/maplibre-gl.css';
import DrawControl from '@/components/DrawControl';

function ConflictMapEditor() {
    const [viewState, setViewState] = useState({
        longitude: 0,
        latitude: 20,
        zoom: 1.5
    });

    const onUpdate = React.useCallback(async (e: any) => {
        // We get the feature collection from the draw instance ideally, 
        // but the event gives us features.
        // We need to access the draw instance to get getAll().
        // Let's use the onDrawReady callback to store the draw instance.
    }, []);

    const [drawInstance, setDrawInstance] = useState<any>(null);

    const saveData = async () => {
        if (!drawInstance) return;
        const data = drawInstance.getAll();
        try {
            await fetch('/api/conflicts', {
                method: 'POST',
                headers: { 'Content-Type': 'application/json' },
                body: JSON.stringify(data)
            });
            console.log('Saved conflict zones');
        } catch (err) {
            console.error('Failed to save', err);
        }
    };

    const onLoad = React.useCallback(async (draw: any) => {
        setDrawInstance(draw);
        // Load initial data
        try {
            const res = await fetch('/api/conflicts');
            const data = await res.json();
            if (data && data.features) {
                draw.add(data);
            }
        } catch (err) {
            console.error('Failed to load conflicts', err);
        }
    }, []);

    return (
        <div className="relative w-full h-full">
            <Map
                {...viewState}
                onMove={evt => setViewState(evt.viewState)}
                mapStyle="https://basemaps.cartocdn.com/gl/dark-matter-gl-style/style.json"
                style={{ width: '100%', height: '100%' }}
            >
                <DrawControl
                    onDrawReady={onLoad}
                    onCreate={saveData}
                    onUpdate={saveData}
                    onDelete={saveData}
                />
                <NavigationControl position="top-right" />
            </Map>
        </div>
    );
}
